# Generated by Django 4.0.4 on 2022-05-08 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_bank', models.CharField(max_length=100)),
                ('origin_agency', models.CharField(max_length=100)),
                ('origin_account', models.CharField(max_length=100)),
                ('destiny_bank', models.CharField(max_length=100)),
                ('destiny_agency', models.CharField(max_length=100)),
                ('destiny_account', models.CharField(max_length=100)),
                ('transaction_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('transaction_date_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DayProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.transaction')),
            ],
        ),
    ]
