# Generated by Django 4.0.4 on 2022-05-08 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayprocess',
            name='transaction',
        ),
        migrations.AddField(
            model_name='transaction',
            name='day_process',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.dayprocess'),
            preserve_default=False,
        ),
    ]
