# Generated by Django 4.0.4 on 2022-05-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_dayprocess_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayprocess',
            name='process_date',
            field=models.DateField(auto_now=True),
        ),
    ]
