# Generated by Django 4.0.4 on 2022-05-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dayprocess_process_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayprocess',
            name='process_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
