# Generated by Django 4.0.4 on 2022-05-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_dayprocess_process_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date_time',
            field=models.DateTimeField(),
        ),
    ]
